from django.db import models

# Create your models here.
class Embarque(models.Model):
    semana = models.IntegerField()
    booking = models.CharField(max_length=15, primary_key=True)
    barco = models.CharField(max_length=40)
    naviera = models.CharField(max_length=15)
    cliente = models.CharField(max_length=50)
    destino = models.CharField(max_length=15)
    depot = models.CharField(max_length=15)
    almacen = models.CharField(max_length=15)
    contenedores = models.IntegerField()
    cajas = models.IntegerField()
    marca = models.CharField(max_length=15)
    tipo = models.CharField(max_length=5)
    peso_neto = models.FloatField()
    peso_bruto = models.FloatField()
    fecha_zarpe = models.DateField()
    tte = models.IntegerField()
    eta = models.DateField()
    factura = models.CharField(max_length=35)
    bl = models.CharField(max_length=20)
    liberacion = models.CharField(max_length=10)
    precio = models.FloatField()
    negociacion = models.CharField(max_length=10)
    termino_pago = models.CharField(max_length=15)
    fob = models.FloatField()
    cf = models.FloatField()
    banco = models.CharField(max_length=15)
    envio_docs = models.CharField(max_length=10)
    orden = models.CharField(max_length=10)
    aupc = models.CharField(max_length=10)
    dae = models.CharField(max_length=21)
    estado = models.CharField(max_length=15)
    cutoff_fisico = models.DateTimeField()
    cutoff_doc = models.DateTimeField()
    energia_libre = models.TimeField()
    dayfree_detention = models.IntegerField()
    dayfree_almacenaje = models.IntegerField()
    observaciones = models.TextField(blank=True, null=True)

class Operacion(models.Model):
    embarque = models.ForeignKey(Embarque, on_delete=models.CASCADE)
    comercializador = models.CharField(max_length=25)
    razon_social = models.CharField(max_length=50)
    dia_de_carga = models.DateField()
    zona = models.CharField(max_length=15) 
    productor = models.CharField(max_length=25)
    hacienda = models.CharField(max_length=30)
    ubicacion = models.CharField(max_length=30)
    marca = models.CharField(max_length=15)
    cajas = models.IntegerField()
    peso_neto = models.FloatField()
    carton_desde = models.CharField(max_length=15)
    materiales_desde = models.CharField(max_length=15)
    